/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using sendbird-platform-sdk.Client;
using sendbird-platform-sdk.org.sendbird.client.api;
using sendbird-platform-sdk.Model;

namespace sendbird-platform-sdk.Test
{
    /// <summary>
    ///  Class for testing UserChannelMetadataApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserChannelMetadataApiTests
    {
        private UserChannelMetadataApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserChannelMetadataApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserChannelMetadataApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' UserChannelMetadataApi
            //Assert.IsInstanceOf(typeof(UserChannelMetadataApi), instance);
        }

        
        /// <summary>
        /// Test CreateChannelMetacounter
        /// </summary>
        [Test]
        public void CreateChannelMetacounterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //CreateChannelMetacounterData createChannelMetacounterData = null;
            //var response = instance.CreateChannelMetacounter(channelType, channelUrl, apiToken, createChannelMetacounterData);
            //Assert.IsInstanceOf(typeof(Dictionary<string, SendBirdAdditionalProperties>), response, "response is Dictionary<string, SendBirdAdditionalProperties>");
        }
        
        /// <summary>
        /// Test CreateChannelMetadata
        /// </summary>
        [Test]
        public void CreateChannelMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //CreateChannelMetadataData createChannelMetadataData = null;
            //var response = instance.CreateChannelMetadata(channelType, channelUrl, apiToken, createChannelMetadataData);
            //Assert.IsInstanceOf(typeof(InlineResponse20061), response, "response is InlineResponse20061");
        }
        
        /// <summary>
        /// Test CreateUserMetadata
        /// </summary>
        [Test]
        public void CreateUserMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string apiToken = null;
            //CreateUserMetadataData createUserMetadataData = null;
            //var response = instance.CreateUserMetadata(userId, apiToken, createUserMetadataData);
            //Assert.IsInstanceOf(typeof(InlineResponse20047UserMetadata), response, "response is InlineResponse20047UserMetadata");
        }
        
        /// <summary>
        /// Test DeleteChannelMetacounter
        /// </summary>
        [Test]
        public void DeleteChannelMetacounterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //instance.DeleteChannelMetacounter(channelType, channelUrl, apiToken);
            
        }
        
        /// <summary>
        /// Test DeleteChannelMetacounterByKey
        /// </summary>
        [Test]
        public void DeleteChannelMetacounterByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string key = null;
            //string apiToken = null;
            //instance.DeleteChannelMetacounterByKey(channelType, channelUrl, key, apiToken);
            
        }
        
        /// <summary>
        /// Test DeleteChannelMetadata
        /// </summary>
        [Test]
        public void DeleteChannelMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //string key = null;
            //instance.DeleteChannelMetadata(channelType, channelUrl, apiToken, key);
            
        }
        
        /// <summary>
        /// Test DeleteChannelMetadataByKey
        /// </summary>
        [Test]
        public void DeleteChannelMetadataByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string key = null;
            //string apiToken = null;
            //instance.DeleteChannelMetadataByKey(channelType, channelUrl, key, apiToken);
            
        }
        
        /// <summary>
        /// Test DeleteUserMetadata
        /// </summary>
        [Test]
        public void DeleteUserMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string apiToken = null;
            //string key = null;
            //instance.DeleteUserMetadata(userId, apiToken, key);
            
        }
        
        /// <summary>
        /// Test DeleteUserMetadataByKey
        /// </summary>
        [Test]
        public void DeleteUserMetadataByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string key = null;
            //string apiToken = null;
            //instance.DeleteUserMetadataByKey(userId, key, apiToken);
            
        }
        
        /// <summary>
        /// Test UpdateChannelMetacounter
        /// </summary>
        [Test]
        public void UpdateChannelMetacounterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //UpdateChannelMetacounterData updateChannelMetacounterData = null;
            //var response = instance.UpdateChannelMetacounter(channelType, channelUrl, apiToken, updateChannelMetacounterData);
            //Assert.IsInstanceOf(typeof(Dictionary<string, SendBirdAdditionalProperties>), response, "response is Dictionary<string, SendBirdAdditionalProperties>");
        }
        
        /// <summary>
        /// Test UpdateChannelMetacounterByKey
        /// </summary>
        [Test]
        public void UpdateChannelMetacounterByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string key = null;
            //string apiToken = null;
            //Object body = null;
            //var response = instance.UpdateChannelMetacounterByKey(channelType, channelUrl, key, apiToken, body);
            //Assert.IsInstanceOf(typeof(Dictionary<string, string>), response, "response is Dictionary<string, string>");
        }
        
        /// <summary>
        /// Test UpdateChannelMetadata
        /// </summary>
        [Test]
        public void UpdateChannelMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //UpdateChannelMetadataData updateChannelMetadataData = null;
            //var response = instance.UpdateChannelMetadata(channelType, channelUrl, apiToken, updateChannelMetadataData);
            //Assert.IsInstanceOf(typeof(Dictionary<string, string>), response, "response is Dictionary<string, string>");
        }
        
        /// <summary>
        /// Test UpdateChannelMetadataByKey
        /// </summary>
        [Test]
        public void UpdateChannelMetadataByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string key = null;
            //string apiToken = null;
            //Object body = null;
            //var response = instance.UpdateChannelMetadataByKey(channelType, channelUrl, key, apiToken, body);
            //Assert.IsInstanceOf(typeof(Dictionary<string, string>), response, "response is Dictionary<string, string>");
        }
        
        /// <summary>
        /// Test UpdateUserMetadata
        /// </summary>
        [Test]
        public void UpdateUserMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string apiToken = null;
            //UpdateUserMetadataData updateUserMetadataData = null;
            //var response = instance.UpdateUserMetadata(userId, apiToken, updateUserMetadataData);
            //Assert.IsInstanceOf(typeof(InlineResponse20060), response, "response is InlineResponse20060");
        }
        
        /// <summary>
        /// Test UpdateUserMetadataByKey
        /// </summary>
        [Test]
        public void UpdateUserMetadataByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string key = null;
            //string apiToken = null;
            //Object body = null;
            //var response = instance.UpdateUserMetadataByKey(userId, key, apiToken, body);
            //Assert.IsInstanceOf(typeof(Dictionary<string, string>), response, "response is Dictionary<string, string>");
        }
        
        /// <summary>
        /// Test ViewChannelMetacounter
        /// </summary>
        [Test]
        public void ViewChannelMetacounterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //string key = null;
            //List<string> keys = null;
            //var response = instance.ViewChannelMetacounter(channelType, channelUrl, apiToken, key, keys);
            //Assert.IsInstanceOf(typeof(Dictionary<string, SendBirdAdditionalProperties>), response, "response is Dictionary<string, SendBirdAdditionalProperties>");
        }
        
        /// <summary>
        /// Test ViewChannelMetacounterByKey
        /// </summary>
        [Test]
        public void ViewChannelMetacounterByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string key = null;
            //string apiToken = null;
            //var response = instance.ViewChannelMetacounterByKey(channelType, channelUrl, key, apiToken);
            //Assert.IsInstanceOf(typeof(Dictionary<string, SendBirdAdditionalProperties>), response, "response is Dictionary<string, SendBirdAdditionalProperties>");
        }
        
        /// <summary>
        /// Test ViewChannelMetadata
        /// </summary>
        [Test]
        public void ViewChannelMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string apiToken = null;
            //string key = null;
            //List<string> keys = null;
            //var response = instance.ViewChannelMetadata(channelType, channelUrl, apiToken, key, keys);
            //Assert.IsInstanceOf(typeof(Dictionary<string, string>), response, "response is Dictionary<string, string>");
        }
        
        /// <summary>
        /// Test ViewChannelMetadataByKey
        /// </summary>
        [Test]
        public void ViewChannelMetadataByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelType = null;
            //string channelUrl = null;
            //string key = null;
            //string apiToken = null;
            //var response = instance.ViewChannelMetadataByKey(channelType, channelUrl, key, apiToken);
            //Assert.IsInstanceOf(typeof(Dictionary<string, string>), response, "response is Dictionary<string, string>");
        }
        
        /// <summary>
        /// Test ViewUserMetadata
        /// </summary>
        [Test]
        public void ViewUserMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string apiToken = null;
            //string key = null;
            //List<string> keys = null;
            //var response = instance.ViewUserMetadata(userId, apiToken, key, keys);
            //Assert.IsInstanceOf(typeof(InlineResponse20047UserMetadata), response, "response is InlineResponse20047UserMetadata");
        }
        
        /// <summary>
        /// Test ViewUserMetadataByKey
        /// </summary>
        [Test]
        public void ViewUserMetadataByKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string key = null;
            //string apiToken = null;
            //var response = instance.ViewUserMetadataByKey(userId, key, apiToken);
            //Assert.IsInstanceOf(typeof(Dictionary<string, string>), response, "response is Dictionary<string, string>");
        }
        
    }

}
