/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = sendbird_platform_sdk.Client.OpenAPIDateConverter;

namespace sendbird_platform_sdk.Model
{
    /// <summary>
    /// UpdateHmsPushConfigurationByIdData
    /// </summary>
    [DataContract]
    public partial class UpdateHmsPushConfigurationByIdData :  IEquatable<UpdateHmsPushConfigurationByIdData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateHmsPushConfigurationByIdData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateHmsPushConfigurationByIdData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateHmsPushConfigurationByIdData" /> class.
        /// </summary>
        /// <param name="providerId">Specifies the provider ID of the push configuration to update. (required).</param>
        /// <param name="huaweiAppId">Specifies the unique ID of application for HMS to update. (required).</param>
        /// <param name="huaweiAppSecret">Specifies the secret key of the application to update. (required).</param>
        /// <param name="pushSound">Specifies the name of a sound file to be played when a push notification is delivered to your client app. The file should be located in the &#x60;/res/raw&#x60; folder. (required).</param>
        public UpdateHmsPushConfigurationByIdData(string providerId = default, string huaweiAppId = default, string huaweiAppSecret = default, string pushSound = default)
        {
            // to ensure "providerId" is required (not null)
            if (providerId == null)
            {
                throw new InvalidDataException("providerId is a required property for UpdateHmsPushConfigurationByIdData and cannot be null");
            }
            else
            {
                this.ProviderId = providerId;
            }

            // to ensure "huaweiAppId" is required (not null)
            if (huaweiAppId == null)
            {
                throw new InvalidDataException("huaweiAppId is a required property for UpdateHmsPushConfigurationByIdData and cannot be null");
            }
            else
            {
                this.HuaweiAppId = huaweiAppId;
            }

            // to ensure "huaweiAppSecret" is required (not null)
            if (huaweiAppSecret == null)
            {
                throw new InvalidDataException("huaweiAppSecret is a required property for UpdateHmsPushConfigurationByIdData and cannot be null");
            }
            else
            {
                this.HuaweiAppSecret = huaweiAppSecret;
            }

            // to ensure "pushSound" is required (not null)
            if (pushSound == null)
            {
                throw new InvalidDataException("pushSound is a required property for UpdateHmsPushConfigurationByIdData and cannot be null");
            }
            else
            {
                this.PushSound = pushSound;
            }

        }

        /// <summary>
        /// Specifies the provider ID of the push configuration to update.
        /// </summary>
        /// <value>Specifies the provider ID of the push configuration to update.</value>
        [DataMember(Name="provider_id", EmitDefaultValue=true)]
        public string ProviderId { get; set; }

        /// <summary>
        /// Specifies the unique ID of application for HMS to update.
        /// </summary>
        /// <value>Specifies the unique ID of application for HMS to update.</value>
        [DataMember(Name="huawei_app_id", EmitDefaultValue=true)]
        public string HuaweiAppId { get; set; }

        /// <summary>
        /// Specifies the secret key of the application to update.
        /// </summary>
        /// <value>Specifies the secret key of the application to update.</value>
        [DataMember(Name="huawei_app_secret", EmitDefaultValue=true)]
        public string HuaweiAppSecret { get; set; }

        /// <summary>
        /// Specifies the name of a sound file to be played when a push notification is delivered to your client app. The file should be located in the &#x60;/res/raw&#x60; folder.
        /// </summary>
        /// <value>Specifies the name of a sound file to be played when a push notification is delivered to your client app. The file should be located in the &#x60;/res/raw&#x60; folder.</value>
        [DataMember(Name="push_sound", EmitDefaultValue=true)]
        public string PushSound { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateHmsPushConfigurationByIdData {\n");
            sb.Append("  ProviderId: ").Append(ProviderId).Append("\n");
            sb.Append("  HuaweiAppId: ").Append(HuaweiAppId).Append("\n");
            sb.Append("  HuaweiAppSecret: ").Append(HuaweiAppSecret).Append("\n");
            sb.Append("  PushSound: ").Append(PushSound).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateHmsPushConfigurationByIdData);
        }

        /// <summary>
        /// Returns true if UpdateHmsPushConfigurationByIdData instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateHmsPushConfigurationByIdData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateHmsPushConfigurationByIdData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProviderId == input.ProviderId ||
                    (this.ProviderId != null &&
                    this.ProviderId.Equals(input.ProviderId))
                ) && 
                (
                    this.HuaweiAppId == input.HuaweiAppId ||
                    (this.HuaweiAppId != null &&
                    this.HuaweiAppId.Equals(input.HuaweiAppId))
                ) && 
                (
                    this.HuaweiAppSecret == input.HuaweiAppSecret ||
                    (this.HuaweiAppSecret != null &&
                    this.HuaweiAppSecret.Equals(input.HuaweiAppSecret))
                ) && 
                (
                    this.PushSound == input.PushSound ||
                    (this.PushSound != null &&
                    this.PushSound.Equals(input.PushSound))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProviderId != null)
                    hashCode = hashCode * 59 + this.ProviderId.GetHashCode();
                if (this.HuaweiAppId != null)
                    hashCode = hashCode * 59 + this.HuaweiAppId.GetHashCode();
                if (this.HuaweiAppSecret != null)
                    hashCode = hashCode * 59 + this.HuaweiAppSecret.GetHashCode();
                if (this.PushSound != null)
                    hashCode = hashCode * 59 + this.PushSound.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
