/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = sendbird_platform_sdk.Client.OpenAPIDateConverter;

namespace sendbird_platform_sdk.Model
{
    /// <summary>
    /// UpdateCountPreferenceOfChannelByUrlResponse
    /// </summary>
    [DataContract]
    public partial class UpdateCountPreferenceOfChannelByUrlResponse :  IEquatable<UpdateCountPreferenceOfChannelByUrlResponse>, IValidatableObject
    {
        /// <summary>
        /// Defines CountPreference
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CountPreferenceEnum
        {
            /// <summary>
            /// Enum False for value: false
            /// </summary>
            [EnumMember(Value = "false")]
            False = 1,

            /// <summary>
            /// Enum All for value: all
            /// </summary>
            [EnumMember(Value = "all")]
            All = 2,

            /// <summary>
            /// Enum Unreadmessagecountonly for value: unread_message_count_only
            /// </summary>
            [EnumMember(Value = "unread_message_count_only")]
            Unreadmessagecountonly = 3,

            /// <summary>
            /// Enum Unreadmentionedcountonly for value: unread_mentioned_count_only
            /// </summary>
            [EnumMember(Value = "unread_mentioned_count_only")]
            Unreadmentionedcountonly = 4

        }

        /// <summary>
        /// Gets or Sets CountPreference
        /// </summary>
        [DataMember(Name="count_preference", EmitDefaultValue=false)]
        public CountPreferenceEnum? CountPreference { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCountPreferenceOfChannelByUrlResponse" /> class.
        /// </summary>
        /// <param name="countPreference">countPreference.</param>
        public UpdateCountPreferenceOfChannelByUrlResponse(CountPreferenceEnum? countPreference = default(CountPreferenceEnum?))
        {
            this.CountPreference = countPreference;
        }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateCountPreferenceOfChannelByUrlResponse {\n");
            sb.Append("  CountPreference: ").Append(CountPreference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateCountPreferenceOfChannelByUrlResponse);
        }

        /// <summary>
        /// Returns true if UpdateCountPreferenceOfChannelByUrlResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateCountPreferenceOfChannelByUrlResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateCountPreferenceOfChannelByUrlResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CountPreference == input.CountPreference ||
                    (this.CountPreference != null &&
                    this.CountPreference.Equals(input.CountPreference))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CountPreference != null)
                    hashCode = hashCode * 59 + this.CountPreference.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
