/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using sendbird_platform_sdk.Client;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing ModerationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ModerationApiTests
    {
        private ModerationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ModerationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModerationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' ModerationApi
            //Assert.IsInstanceOf(typeof(ModerationApi), instance);
        }

        
        /// <summary>
        /// Test BlockAUser
        /// </summary>
        [Test]
        public void BlockAUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string apiToken = null;
            //BlockAUserRequest blockAUserRequest = null;
            //var response = instance.BlockAUser(userId, apiToken, blockAUserRequest);
            //Assert.IsInstanceOf(typeof(BlockAUserResponse), response, "response is BlockAUserResponse");
        }
        
        /// <summary>
        /// Test FreezeAGroupChannel
        /// </summary>
        [Test]
        public void FreezeAGroupChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelUrl = null;
            //string apiToken = null;
            //FreezeAGroupChannelRequest freezeAGroupChannelRequest = null;
            //var response = instance.FreezeAGroupChannel(channelUrl, apiToken, freezeAGroupChannelRequest);
            //Assert.IsInstanceOf(typeof(SendbirdGroupChannelDetail), response, "response is SendbirdGroupChannelDetail");
        }
        
        /// <summary>
        /// Test FreezeAnOpenChannel
        /// </summary>
        [Test]
        public void FreezeAnOpenChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelUrl = null;
            //string apiToken = null;
            //FreezeAnOpenChannelRequest freezeAnOpenChannelRequest = null;
            //var response = instance.FreezeAnOpenChannel(channelUrl, apiToken, freezeAnOpenChannelRequest);
            //Assert.IsInstanceOf(typeof(SendbirdOpenChannel), response, "response is SendbirdOpenChannel");
        }
        
        /// <summary>
        /// Test ListBlockedUsers
        /// </summary>
        [Test]
        public void ListBlockedUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string list = null;
            //string token = null;
            //int? limit = null;
            //string userIds = null;
            //string metadatakey = null;
            //string metadatavaluesIn = null;
            //string apiToken = null;
            //var response = instance.ListBlockedUsers(userId, list, token, limit, userIds, metadatakey, metadatavaluesIn, apiToken);
            //Assert.IsInstanceOf(typeof(ListBlockedUsersResponse), response, "response is ListBlockedUsersResponse");
        }
        
        /// <summary>
        /// Test UnblockAUser
        /// </summary>
        [Test]
        public void UnblockAUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //string targetId = null;
            //string apiToken = null;
            //var response = instance.UnblockAUser(userId, targetId, apiToken);
            //Assert.IsInstanceOf(typeof(Object), response, "response is Object");
        }
        
    }

}
