/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird-platform-sdk.Api;
using sendbird-platform-sdk.Model;
using sendbird-platform-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird-platform-sdk.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20011
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse20011Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20011
        //private InlineResponse20011 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20011
            //instance = new InlineResponse20011();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20011
        /// </summary>
        [Test]
        public void InlineResponse20011InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse20011
            //Assert.IsInstanceOf(typeof(InlineResponse20011), instance);
        }


        /// <summary>
        /// Test the property 'Dau'
        /// </summary>
        [Test]
        public void DauTest()
        {
            // TODO unit test for the property 'Dau'
        }

    }

}
