/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird-platform-sdk.Api;
using sendbird-platform-sdk.Model;
using sendbird-platform-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird-platform-sdk.Test
{
    /// <summary>
    ///  Class for testing SendBirdMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendBirdMessageResponseTests
    {
        // TODO uncomment below to declare an instance variable for SendBirdMessageResponse
        //private SendBirdMessageResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendBirdMessageResponse
            //instance = new SendBirdMessageResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendBirdMessageResponse
        /// </summary>
        [Test]
        public void SendBirdMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SendBirdMessageResponse
            //Assert.IsInstanceOf(typeof(SendBirdMessageResponse), instance);
        }


        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
