/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing AddHmsPushConfigurationData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddHmsPushConfigurationDataTests
    {
        // TODO uncomment below to declare an instance variable for AddHmsPushConfigurationData
        //private AddHmsPushConfigurationData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddHmsPushConfigurationData
            //instance = new AddHmsPushConfigurationData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddHmsPushConfigurationData
        /// </summary>
        [Test]
        public void AddHmsPushConfigurationDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AddHmsPushConfigurationData
            //Assert.IsInstanceOf(typeof(AddHmsPushConfigurationData), instance);
        }


        /// <summary>
        /// Test the property 'HuaweiAppId'
        /// </summary>
        [Test]
        public void HuaweiAppIdTest()
        {
            // TODO unit test for the property 'HuaweiAppId'
        }
        /// <summary>
        /// Test the property 'HuaweiAppSecret'
        /// </summary>
        [Test]
        public void HuaweiAppSecretTest()
        {
            // TODO unit test for the property 'HuaweiAppSecret'
        }
        /// <summary>
        /// Test the property 'PushSound'
        /// </summary>
        [Test]
        public void PushSoundTest()
        {
            // TODO unit test for the property 'PushSound'
        }

    }

}
