/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing CreateABotResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateABotResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateABotResponse
        //private CreateABotResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateABotResponse
            //instance = new CreateABotResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateABotResponse
        /// </summary>
        [Test]
        public void CreateABotResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateABotResponse
            //Assert.IsInstanceOf(typeof(CreateABotResponse), instance);
        }


        /// <summary>
        /// Test the property 'Bot'
        /// </summary>
        [Test]
        public void BotTest()
        {
            // TODO unit test for the property 'Bot'
        }
        /// <summary>
        /// Test the property 'BotCallbackUrl'
        /// </summary>
        [Test]
        public void BotCallbackUrlTest()
        {
            // TODO unit test for the property 'BotCallbackUrl'
        }
        /// <summary>
        /// Test the property 'BotStyle'
        /// </summary>
        [Test]
        public void BotStyleTest()
        {
            // TODO unit test for the property 'BotStyle'
        }
        /// <summary>
        /// Test the property 'ChannelInvitationPreference'
        /// </summary>
        [Test]
        public void ChannelInvitationPreferenceTest()
        {
            // TODO unit test for the property 'ChannelInvitationPreference'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'EnableMarkAsRead'
        /// </summary>
        [Test]
        public void EnableMarkAsReadTest()
        {
            // TODO unit test for the property 'EnableMarkAsRead'
        }
        /// <summary>
        /// Test the property 'IsPrivacyMode'
        /// </summary>
        [Test]
        public void IsPrivacyModeTest()
        {
            // TODO unit test for the property 'IsPrivacyMode'
        }
        /// <summary>
        /// Test the property 'ShowMember'
        /// </summary>
        [Test]
        public void ShowMemberTest()
        {
            // TODO unit test for the property 'ShowMember'
        }

    }

}
