/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20068
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse20068Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20068
        //private InlineResponse20068 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20068
            //instance = new InlineResponse20068();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20068
        /// </summary>
        [Test]
        public void InlineResponse20068InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse20068
            //Assert.IsInstanceOf(typeof(InlineResponse20068), instance);
        }


        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Test]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Test]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

    }

}
