/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing ListAllEmojisAndEmojiCategoriesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListAllEmojisAndEmojiCategoriesResponseTests
    {
        // TODO uncomment below to declare an instance variable for ListAllEmojisAndEmojiCategoriesResponse
        //private ListAllEmojisAndEmojiCategoriesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListAllEmojisAndEmojiCategoriesResponse
            //instance = new ListAllEmojisAndEmojiCategoriesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListAllEmojisAndEmojiCategoriesResponse
        /// </summary>
        [Test]
        public void ListAllEmojisAndEmojiCategoriesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListAllEmojisAndEmojiCategoriesResponse
            //Assert.IsInstanceOf(typeof(ListAllEmojisAndEmojiCategoriesResponse), instance);
        }


        /// <summary>
        /// Test the property 'EmojiHash'
        /// </summary>
        [Test]
        public void EmojiHashTest()
        {
            // TODO unit test for the property 'EmojiHash'
        }
        /// <summary>
        /// Test the property 'EmojiCategories'
        /// </summary>
        [Test]
        public void EmojiCategoriesTest()
        {
            // TODO unit test for the property 'EmojiCategories'
        }

    }

}
