/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing ListBotsResponseBotsInnerSafeguard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListBotsResponseBotsInnerSafeguardTests
    {
        // TODO uncomment below to declare an instance variable for ListBotsResponseBotsInnerSafeguard
        //private ListBotsResponseBotsInnerSafeguard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListBotsResponseBotsInnerSafeguard
            //instance = new ListBotsResponseBotsInnerSafeguard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListBotsResponseBotsInnerSafeguard
        /// </summary>
        [Test]
        public void ListBotsResponseBotsInnerSafeguardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListBotsResponseBotsInnerSafeguard
            //Assert.IsInstanceOf(typeof(ListBotsResponseBotsInnerSafeguard), instance);
        }


        /// <summary>
        /// Test the property 'BannedPhrases'
        /// </summary>
        [Test]
        public void BannedPhrasesTest()
        {
            // TODO unit test for the property 'BannedPhrases'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'PiiMasking'
        /// </summary>
        [Test]
        public void PiiMaskingTest()
        {
            // TODO unit test for the property 'PiiMasking'
        }

    }

}
