/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing ListSecondaryApiTokensResponseApiTokens
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListSecondaryApiTokensResponseApiTokensTests
    {
        // TODO uncomment below to declare an instance variable for ListSecondaryApiTokensResponseApiTokens
        //private ListSecondaryApiTokensResponseApiTokens instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListSecondaryApiTokensResponseApiTokens
            //instance = new ListSecondaryApiTokensResponseApiTokens();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListSecondaryApiTokensResponseApiTokens
        /// </summary>
        [Test]
        public void ListSecondaryApiTokensResponseApiTokensInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListSecondaryApiTokensResponseApiTokens
            //Assert.IsInstanceOf(typeof(ListSecondaryApiTokensResponseApiTokens), instance);
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
