/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing ListDataExportsByMessageChannelOrUserResponseExportedData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListDataExportsByMessageChannelOrUserResponseExportedDataTests
    {
        // TODO uncomment below to declare an instance variable for ListDataExportsByMessageChannelOrUserResponseExportedData
        //private ListDataExportsByMessageChannelOrUserResponseExportedData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListDataExportsByMessageChannelOrUserResponseExportedData
            //instance = new ListDataExportsByMessageChannelOrUserResponseExportedData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListDataExportsByMessageChannelOrUserResponseExportedData
        /// </summary>
        [Test]
        public void ListDataExportsByMessageChannelOrUserResponseExportedDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListDataExportsByMessageChannelOrUserResponseExportedData
            //Assert.IsInstanceOf(typeof(ListDataExportsByMessageChannelOrUserResponseExportedData), instance);
        }


        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'CsvDelimiter'
        /// </summary>
        [Test]
        public void CsvDelimiterTest()
        {
            // TODO unit test for the property 'CsvDelimiter'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'StartTs'
        /// </summary>
        [Test]
        public void StartTsTest()
        {
            // TODO unit test for the property 'StartTs'
        }
        /// <summary>
        /// Test the property 'EndTs'
        /// </summary>
        [Test]
        public void EndTsTest()
        {
            // TODO unit test for the property 'EndTs'
        }
        /// <summary>
        /// Test the property 'ChannelUrls'
        /// </summary>
        [Test]
        public void ChannelUrlsTest()
        {
            // TODO unit test for the property 'ChannelUrls'
        }
        /// <summary>
        /// Test the property 'SenderIds'
        /// </summary>
        [Test]
        public void SenderIdsTest()
        {
            // TODO unit test for the property 'SenderIds'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'UserIds'
        /// </summary>
        [Test]
        public void UserIdsTest()
        {
            // TODO unit test for the property 'UserIds'
        }

    }

}
