/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing ListAllEmojisAndEmojiCategoriesResponseEmojiCategories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListAllEmojisAndEmojiCategoriesResponseEmojiCategoriesTests
    {
        // TODO uncomment below to declare an instance variable for ListAllEmojisAndEmojiCategoriesResponseEmojiCategories
        //private ListAllEmojisAndEmojiCategoriesResponseEmojiCategories instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListAllEmojisAndEmojiCategoriesResponseEmojiCategories
            //instance = new ListAllEmojisAndEmojiCategoriesResponseEmojiCategories();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListAllEmojisAndEmojiCategoriesResponseEmojiCategories
        /// </summary>
        [Test]
        public void ListAllEmojisAndEmojiCategoriesResponseEmojiCategoriesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListAllEmojisAndEmojiCategoriesResponseEmojiCategories
            //Assert.IsInstanceOf(typeof(ListAllEmojisAndEmojiCategoriesResponseEmojiCategories), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Emojis'
        /// </summary>
        [Test]
        public void EmojisTest()
        {
            // TODO unit test for the property 'Emojis'
        }

    }

}
