/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing OcRegisterOperatorsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OcRegisterOperatorsDataTests
    {
        // TODO uncomment below to declare an instance variable for OcRegisterOperatorsData
        //private OcRegisterOperatorsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OcRegisterOperatorsData
            //instance = new OcRegisterOperatorsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OcRegisterOperatorsData
        /// </summary>
        [Test]
        public void OcRegisterOperatorsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" OcRegisterOperatorsData
            //Assert.IsInstanceOf(typeof(OcRegisterOperatorsData), instance);
        }


        /// <summary>
        /// Test the property 'ChannelUrl'
        /// </summary>
        [Test]
        public void ChannelUrlTest()
        {
            // TODO unit test for the property 'ChannelUrl'
        }
        /// <summary>
        /// Test the property 'OperatorIds'
        /// </summary>
        [Test]
        public void OperatorIdsTest()
        {
            // TODO unit test for the property 'OperatorIds'
        }

    }

}
