/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing ScheduleAnAnnouncementRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleAnAnnouncementRequestTests
    {
        // TODO uncomment below to declare an instance variable for ScheduleAnAnnouncementRequest
        //private ScheduleAnAnnouncementRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduleAnAnnouncementRequest
            //instance = new ScheduleAnAnnouncementRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduleAnAnnouncementRequest
        /// </summary>
        [Test]
        public void ScheduleAnAnnouncementRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ScheduleAnAnnouncementRequest
            //Assert.IsInstanceOf(typeof(ScheduleAnAnnouncementRequest), instance);
        }


        /// <summary>
        /// Test the property 'AnnouncementGroup'
        /// </summary>
        [Test]
        public void AnnouncementGroupTest()
        {
            // TODO unit test for the property 'AnnouncementGroup'
        }
        /// <summary>
        /// Test the property 'AssignSenderAsChannelInviter'
        /// </summary>
        [Test]
        public void AssignSenderAsChannelInviterTest()
        {
            // TODO unit test for the property 'AssignSenderAsChannelInviter'
        }
        /// <summary>
        /// Test the property 'CeaseAt'
        /// </summary>
        [Test]
        public void CeaseAtTest()
        {
            // TODO unit test for the property 'CeaseAt'
        }
        /// <summary>
        /// Test the property 'CreateChannel'
        /// </summary>
        [Test]
        public void CreateChannelTest()
        {
            // TODO unit test for the property 'CreateChannel'
        }
        /// <summary>
        /// Test the property 'CreateChannelOptions'
        /// </summary>
        [Test]
        public void CreateChannelOptionsTest()
        {
            // TODO unit test for the property 'CreateChannelOptions'
        }
        /// <summary>
        /// Test the property 'EnablePush'
        /// </summary>
        [Test]
        public void EnablePushTest()
        {
            // TODO unit test for the property 'EnablePush'
        }
        /// <summary>
        /// Test the property 'EndAt'
        /// </summary>
        [Test]
        public void EndAtTest()
        {
            // TODO unit test for the property 'EndAt'
        }
        /// <summary>
        /// Test the property 'KeepChannelHiddenForSender'
        /// </summary>
        [Test]
        public void KeepChannelHiddenForSenderTest()
        {
            // TODO unit test for the property 'KeepChannelHiddenForSender'
        }
        /// <summary>
        /// Test the property 'MarkAsRead'
        /// </summary>
        [Test]
        public void MarkAsReadTest()
        {
            // TODO unit test for the property 'MarkAsRead'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'ResumeAt'
        /// </summary>
        [Test]
        public void ResumeAtTest()
        {
            // TODO unit test for the property 'ResumeAt'
        }
        /// <summary>
        /// Test the property 'ScheduledAt'
        /// </summary>
        [Test]
        public void ScheduledAtTest()
        {
            // TODO unit test for the property 'ScheduledAt'
        }
        /// <summary>
        /// Test the property 'SendToFrozenChannels'
        /// </summary>
        [Test]
        public void SendToFrozenChannelsTest()
        {
            // TODO unit test for the property 'SendToFrozenChannels'
        }
        /// <summary>
        /// Test the property 'TargetAt'
        /// </summary>
        [Test]
        public void TargetAtTest()
        {
            // TODO unit test for the property 'TargetAt'
        }
        /// <summary>
        /// Test the property 'TargetChannelType'
        /// </summary>
        [Test]
        public void TargetChannelTypeTest()
        {
            // TODO unit test for the property 'TargetChannelType'
        }
        /// <summary>
        /// Test the property 'TargetCustomType'
        /// </summary>
        [Test]
        public void TargetCustomTypeTest()
        {
            // TODO unit test for the property 'TargetCustomType'
        }
        /// <summary>
        /// Test the property 'TargetList'
        /// </summary>
        [Test]
        public void TargetListTest()
        {
            // TODO unit test for the property 'TargetList'
        }
        /// <summary>
        /// Test the property 'UniqueId'
        /// </summary>
        [Test]
        public void UniqueIdTest()
        {
            // TODO unit test for the property 'UniqueId'
        }

    }

}
