/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing SendBirdChannelResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendBirdChannelResponseTests
    {
        // TODO uncomment below to declare an instance variable for SendBirdChannelResponse
        //private SendBirdChannelResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendBirdChannelResponse
            //instance = new SendBirdChannelResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendBirdChannelResponse
        /// </summary>
        [Test]
        public void SendBirdChannelResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SendBirdChannelResponse
            //Assert.IsInstanceOf(typeof(SendBirdChannelResponse), instance);
        }


        /// <summary>
        /// Test the property 'ChannelUrl'
        /// </summary>
        [Test]
        public void ChannelUrlTest()
        {
            // TODO unit test for the property 'ChannelUrl'
        }
        /// <summary>
        /// Test the property 'CoverUrl'
        /// </summary>
        [Test]
        public void CoverUrlTest()
        {
            // TODO unit test for the property 'CoverUrl'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Test]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'CustomType'
        /// </summary>
        [Test]
        public void CustomTypeTest()
        {
            // TODO unit test for the property 'CustomType'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'DisappearingMessage'
        /// </summary>
        [Test]
        public void DisappearingMessageTest()
        {
            // TODO unit test for the property 'DisappearingMessage'
        }
        /// <summary>
        /// Test the property 'Freeze'
        /// </summary>
        [Test]
        public void FreezeTest()
        {
            // TODO unit test for the property 'Freeze'
        }
        /// <summary>
        /// Test the property 'IgnoreProfanityFilter'
        /// </summary>
        [Test]
        public void IgnoreProfanityFilterTest()
        {
            // TODO unit test for the property 'IgnoreProfanityFilter'
        }
        /// <summary>
        /// Test the property 'HiddenState'
        /// </summary>
        [Test]
        public void HiddenStateTest()
        {
            // TODO unit test for the property 'HiddenState'
        }
        /// <summary>
        /// Test the property 'InvitedAt'
        /// </summary>
        [Test]
        public void InvitedAtTest()
        {
            // TODO unit test for the property 'InvitedAt'
        }
        /// <summary>
        /// Test the property 'Inviter'
        /// </summary>
        [Test]
        public void InviterTest()
        {
            // TODO unit test for the property 'Inviter'
        }
        /// <summary>
        /// Test the property 'IsAccessCodeRequired'
        /// </summary>
        [Test]
        public void IsAccessCodeRequiredTest()
        {
            // TODO unit test for the property 'IsAccessCodeRequired'
        }
        /// <summary>
        /// Test the property 'IsBroadcast'
        /// </summary>
        [Test]
        public void IsBroadcastTest()
        {
            // TODO unit test for the property 'IsBroadcast'
        }
        /// <summary>
        /// Test the property 'IsCreated'
        /// </summary>
        [Test]
        public void IsCreatedTest()
        {
            // TODO unit test for the property 'IsCreated'
        }
        /// <summary>
        /// Test the property 'IsDiscoverable'
        /// </summary>
        [Test]
        public void IsDiscoverableTest()
        {
            // TODO unit test for the property 'IsDiscoverable'
        }
        /// <summary>
        /// Test the property 'IsDistinct'
        /// </summary>
        [Test]
        public void IsDistinctTest()
        {
            // TODO unit test for the property 'IsDistinct'
        }
        /// <summary>
        /// Test the property 'IsEphemeral'
        /// </summary>
        [Test]
        public void IsEphemeralTest()
        {
            // TODO unit test for the property 'IsEphemeral'
        }
        /// <summary>
        /// Test the property 'IsFrozen'
        /// </summary>
        [Test]
        public void IsFrozenTest()
        {
            // TODO unit test for the property 'IsFrozen'
        }
        /// <summary>
        /// Test the property 'IsHidden'
        /// </summary>
        [Test]
        public void IsHiddenTest()
        {
            // TODO unit test for the property 'IsHidden'
        }
        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Test]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }
        /// <summary>
        /// Test the property 'IsPushEnabled'
        /// </summary>
        [Test]
        public void IsPushEnabledTest()
        {
            // TODO unit test for the property 'IsPushEnabled'
        }
        /// <summary>
        /// Test the property 'IsSuper'
        /// </summary>
        [Test]
        public void IsSuperTest()
        {
            // TODO unit test for the property 'IsSuper'
        }
        /// <summary>
        /// Test the property 'JoinedAt'
        /// </summary>
        [Test]
        public void JoinedAtTest()
        {
            // TODO unit test for the property 'JoinedAt'
        }
        /// <summary>
        /// Test the property 'JoinedMemberCount'
        /// </summary>
        [Test]
        public void JoinedMemberCountTest()
        {
            // TODO unit test for the property 'JoinedMemberCount'
        }
        /// <summary>
        /// Test the property 'LastMessage'
        /// </summary>
        [Test]
        public void LastMessageTest()
        {
            // TODO unit test for the property 'LastMessage'
        }
        /// <summary>
        /// Test the property 'MaxLengthMessage'
        /// </summary>
        [Test]
        public void MaxLengthMessageTest()
        {
            // TODO unit test for the property 'MaxLengthMessage'
        }
        /// <summary>
        /// Test the property 'MemberCount'
        /// </summary>
        [Test]
        public void MemberCountTest()
        {
            // TODO unit test for the property 'MemberCount'
        }
        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Test]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }
        /// <summary>
        /// Test the property 'MessageOffsetTimestamp'
        /// </summary>
        [Test]
        public void MessageOffsetTimestampTest()
        {
            // TODO unit test for the property 'MessageOffsetTimestamp'
        }
        /// <summary>
        /// Test the property 'MessageSurvivalSeconds'
        /// </summary>
        [Test]
        public void MessageSurvivalSecondsTest()
        {
            // TODO unit test for the property 'MessageSurvivalSeconds'
        }
        /// <summary>
        /// Test the property 'MyCountPreference'
        /// </summary>
        [Test]
        public void MyCountPreferenceTest()
        {
            // TODO unit test for the property 'MyCountPreference'
        }
        /// <summary>
        /// Test the property 'MyLastRead'
        /// </summary>
        [Test]
        public void MyLastReadTest()
        {
            // TODO unit test for the property 'MyLastRead'
        }
        /// <summary>
        /// Test the property 'MyMemberState'
        /// </summary>
        [Test]
        public void MyMemberStateTest()
        {
            // TODO unit test for the property 'MyMemberState'
        }
        /// <summary>
        /// Test the property 'MyMutedState'
        /// </summary>
        [Test]
        public void MyMutedStateTest()
        {
            // TODO unit test for the property 'MyMutedState'
        }
        /// <summary>
        /// Test the property 'MyPushTriggerOption'
        /// </summary>
        [Test]
        public void MyPushTriggerOptionTest()
        {
            // TODO unit test for the property 'MyPushTriggerOption'
        }
        /// <summary>
        /// Test the property 'MyRole'
        /// </summary>
        [Test]
        public void MyRoleTest()
        {
            // TODO unit test for the property 'MyRole'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Operators'
        /// </summary>
        [Test]
        public void OperatorsTest()
        {
            // TODO unit test for the property 'Operators'
        }
        /// <summary>
        /// Test the property 'SmsFallback'
        /// </summary>
        [Test]
        public void SmsFallbackTest()
        {
            // TODO unit test for the property 'SmsFallback'
        }
        /// <summary>
        /// Test the property 'UnreadMentionCount'
        /// </summary>
        [Test]
        public void UnreadMentionCountTest()
        {
            // TODO unit test for the property 'UnreadMentionCount'
        }
        /// <summary>
        /// Test the property 'UnreadMessageCount'
        /// </summary>
        [Test]
        public void UnreadMessageCountTest()
        {
            // TODO unit test for the property 'UnreadMessageCount'
        }
        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Test]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
        /// <summary>
        /// Test the property 'IsDynamicPartitioned'
        /// </summary>
        [Test]
        public void IsDynamicPartitionedTest()
        {
            // TODO unit test for the property 'IsDynamicPartitioned'
        }
        /// <summary>
        /// Test the property 'ParticipantCount'
        /// </summary>
        [Test]
        public void ParticipantCountTest()
        {
            // TODO unit test for the property 'ParticipantCount'
        }

    }

}
