/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing SendbirdMessageResponseMessageEvents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendbirdMessageResponseMessageEventsTests
    {
        // TODO uncomment below to declare an instance variable for SendbirdMessageResponseMessageEvents
        //private SendbirdMessageResponseMessageEvents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendbirdMessageResponseMessageEvents
            //instance = new SendbirdMessageResponseMessageEvents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendbirdMessageResponseMessageEvents
        /// </summary>
        [Test]
        public void SendbirdMessageResponseMessageEventsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SendbirdMessageResponseMessageEvents
            //Assert.IsInstanceOf(typeof(SendbirdMessageResponseMessageEvents), instance);
        }


        /// <summary>
        /// Test the property 'SendPushNotification'
        /// </summary>
        [Test]
        public void SendPushNotificationTest()
        {
            // TODO unit test for the property 'SendPushNotification'
        }
        /// <summary>
        /// Test the property 'UpdateUnreadCount'
        /// </summary>
        [Test]
        public void UpdateUnreadCountTest()
        {
            // TODO unit test for the property 'UpdateUnreadCount'
        }
        /// <summary>
        /// Test the property 'UpdateMentionCount'
        /// </summary>
        [Test]
        public void UpdateMentionCountTest()
        {
            // TODO unit test for the property 'UpdateMentionCount'
        }
        /// <summary>
        /// Test the property 'UpdateLastMessage'
        /// </summary>
        [Test]
        public void UpdateLastMessageTest()
        {
            // TODO unit test for the property 'UpdateLastMessage'
        }

    }

}
