/*
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sendbird_platform_sdk.Api;
using sendbird_platform_sdk.Model;
using sendbird_platform_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sendbird_platform_sdk.Test
{
    /// <summary>
    ///  Class for testing UpdateBotByIdData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateBotByIdDataTests
    {
        // TODO uncomment below to declare an instance variable for UpdateBotByIdData
        //private UpdateBotByIdData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateBotByIdData
            //instance = new UpdateBotByIdData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateBotByIdData
        /// </summary>
        [Test]
        public void UpdateBotByIdDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateBotByIdData
            //Assert.IsInstanceOf(typeof(UpdateBotByIdData), instance);
        }


        /// <summary>
        /// Test the property 'BotUserid'
        /// </summary>
        [Test]
        public void BotUseridTest()
        {
            // TODO unit test for the property 'BotUserid'
        }
        /// <summary>
        /// Test the property 'BotNickname'
        /// </summary>
        [Test]
        public void BotNicknameTest()
        {
            // TODO unit test for the property 'BotNickname'
        }
        /// <summary>
        /// Test the property 'BotProfileUrl'
        /// </summary>
        [Test]
        public void BotProfileUrlTest()
        {
            // TODO unit test for the property 'BotProfileUrl'
        }
        /// <summary>
        /// Test the property 'BotCallbackUrl'
        /// </summary>
        [Test]
        public void BotCallbackUrlTest()
        {
            // TODO unit test for the property 'BotCallbackUrl'
        }
        /// <summary>
        /// Test the property 'IsPrivacyMode'
        /// </summary>
        [Test]
        public void IsPrivacyModeTest()
        {
            // TODO unit test for the property 'IsPrivacyMode'
        }
        /// <summary>
        /// Test the property 'EnableMarkAsRead'
        /// </summary>
        [Test]
        public void EnableMarkAsReadTest()
        {
            // TODO unit test for the property 'EnableMarkAsRead'
        }
        /// <summary>
        /// Test the property 'ShowMember'
        /// </summary>
        [Test]
        public void ShowMemberTest()
        {
            // TODO unit test for the property 'ShowMember'
        }
        /// <summary>
        /// Test the property 'ChannelInvitationPreference'
        /// </summary>
        [Test]
        public void ChannelInvitationPreferenceTest()
        {
            // TODO unit test for the property 'ChannelInvitationPreference'
        }

    }

}
